### ISSUE TITLE
USER STORY: View paginated lists of posts

### ISSUE THREAD

**Issue by laurachri-hall** [laurachri-hall/django-blog#1]
As a **site user** I can **view a paginate list of posts** so that **I can select which post I want to view**.

### Acceptance Criteria

- Given more than one post in the database, these multiple posts are listed.
- When a user opens the main page a list of posts is seen.
- Then the user sees all post title with pagination to choose what to read.

### Tasks
- [x] Create a template to display the list of posts
- [x] Add pagination functionality to the view
- [x] Configure the number of posts to display per page
- [x] Implement next and previous page navigation
- [x] Display post titles as clickable links
- [x] Add basic post information (e.g., author, date) to each list item
- [x] Ensure the main page URL is set to display this list
- [x] Test pagination with various numbers of posts
- [x] Verify that clicking a post title leads to the full post view
